### ISSUE TITLE
Why do we have both server and client side render of the same component?

### ISSUE THREAD

**Issue by bryanboyan** [i-like-robots/react-tube-tracker#4]
Hi, Matt

In this example, I see there are both server side render of TubeTracker (app/server/bootstrap.jsx) and client side render of that (app/browser/bootstrap.jsx).
While I know server side rendering only provides static html, will client side refresh the whole pre-rendered static html to react again? Since I guess those pre-rendered DOM are not in "Virtual DOM tree".

I saw some other examples does this way as well, just wonder if that's intentional because of some reasons?

**Comment by i-like-robots** [comment]
It's very much intentional, it's possibly the most important feature of this example app.

For your reference:

- http://maketea.co.uk/2014/03/05/building-robust-web-apps-with-react-part-1.html
- http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/
- http://blog.getify.com/adaptive-hybrid-javascript/
- http://www.sitepoint.com/isomorphic-javascript-applications/

**Comment by Lakshman-LD** [comment]
Isomorphic apps are good. Say, the server-side scripts are rendered using mongo-db and the server-side rendering cannot handle any events. The client-side scripts are pre-compiled and in this case of mongo db input , how do you pass it to the client?? And client-side scripts can only handle the events. So, how is the dynamic input of mongo db given to client-side scipts
